### ISSUE TITLE
configureStore is not a function via module.exports

### ISSUE THREAD

**Issue by Kronenberg** [reduxjs/redux-mock-store#159]
Here is my example
![screen shot 2018-10-10 at 11 53 03](https://user-images.githubusercontent.com/13053374/46724621-1337b480-cc83-11e8-877d-671bcf3ea2b2.png)

I am try to require and run this module but have error:  **TypeError: configureStore is not a function**
With regular import configureStore from 'redux-mock-store' everything works fine.
But i can't use imports in any case. Can somebody help me with that?

**Comment by newyork-anthonyng** [comment]
The `README.md` says to use the below:
```js
const { configureStore } = require('redux-mock-store');
```

**Comment by Kronenberg** [comment]
> The `README.md` says to use the below:
> 
> ```js
> const { configureStore } = require('redux-mock-store');
> ```

I am already try this thing. Its not working.
I am try with default
![screen shot 2018-10-10 at 13 43 46](https://user-images.githubusercontent.com/13053374/46731105-898fe300-cc92-11e8-9163-c2f44fc91ed7.png)
, but i have another error like: **mockStore is not a function**
![screen shot 2018-10-10 at 13 44 16](https://user-images.githubusercontent.com/13053374/46731198-c360e980-cc92-11e8-8cb0-3bf75eb8f34e.png)

**Comment by newyork-anthonyng** [comment]
Can you create a repository that recreates a basic example of this error?

**Comment by Kronenberg** [comment]
> Can you create a repository that recreates a basic example of this error?

Yes ill do this asap.

**Comment by Kronenberg** [comment]
> Can you create a repository that recreates a basic example of this error?

Link: **https://github.com/Kronenberg/redux-thunk-tests-example**
source for example test: **src/actions/PlaceHolderApiActions.test.js**

**Comment by MaxLarue** [comment]
Did you try 
```javascript 
const configureStore = require('redux-mock-store').configureStore 
``` 
?

or 
```javascript
const redux_mock_store = require("redux-mock-store")
const configureStore = redux_mock_store.configureStore
```
Let me knwo ig that worked

**Comment by newyork-anthonyng** [comment]
@Kronenberg Sorry for late response.

It looks like you have a typo in your code.

```js
// 👇 this works for you
import configureMockStore from "redux-mock-store";

// 👇 notice how you named this import "configureStore", rather than "configureMockStore"
const configureStore = require('redux-mock-store').default();
```

I changed the below and it worked.
```diff
- const configureStore = require('redux-mock-store').default();
+ const configureMockStore = require('redux-mock-store').default;
```
I changed the import name from `configureStore` to `configureMockStore`, and changed `default()` to `default`.

**Comment by jednano** [comment]
This should be fixed in my TypeScript fork: https://github.com/dmitry-zaets/redux-mock-store/issues/148#issuecomment-510758916

**Comment by abdul-hamid-achik** [comment]
still not working, im using version 1.5.3

whenever i use it as:

`import configureStore from 'redux-mock-store'`

i get `TypeError: (0 , _reduxMockStore.default) is not a function`

**Comment by jednano** [comment]
Try `import configureStore from "@jedmao/redux-mock-store;` (installation required).

**Comment by abdul-hamid-achik** [comment]
same problem, at this point i think it has something to do with jest and the way i have it configured, do you think i should add this lib to the trransformIgnorePatterns? if i open node and import it manually it works flawlesly but not with jest :(

**Comment by jednano** [comment]
I have it working with Jest [here](https://github.com/jedmao/tsx/blob/22c9a8d9301eb22936f79babe3f07cd1b6cd9513/package.json#L144), FWIW.

**Comment by abdul-hamid-achik** [comment]
same issue, its not working for me, at this point it could really be my setup because no matter how i change the redux-mock-store library, it keep getting the same error

**Comment by abdul-hamid-achik** [comment]
Okay guys sorry for the problems, it was infact a problem on my end, decided to redo the part and got rid of manually mapping my project dependencies for jest and this just went back to work normally, started using `@` as a namespace for my modules... 
thanks for the help, ill leave the screenshot in case someone comes and has the same problem as me, its most likely your `jest.config.json` config at this point
![imagen](https://user-images.githubusercontent.com/7379966/63076635-7b86a080-befb-11e9-82b7-1a3fc8abdb16.png)

**Comment by happysmilecode** [comment]
Please leave your jest config file in more detail.
I have still error.
Thanks.
